### ISSUE TITLE
Error following tutorial executing function

### ISSUE THREAD

**Issue by jjgamboa123** [googlecodelabs/iot-data-pipeline#1]
ERROR: { PartialFailureError: A failure occurred during this request. at /user_code/node_modules/@google-cloud/bigquery/src/table.js:1666:15 at Object.handleResp (/user_code/node_modules/@google-cloud/bigquery/node_modules/@google-cloud/common/src/util.js:134:3) at /user_code/node_modules/@google-cloud/bigquery/node_modules/@google-cloud/common/src/util.js:496:12 at Request.onResponse [as _callback] (/user_code/node_modules/@google-cloud/bigquery/node_modules/retry-request/index.js:195:7) at Request.self.callback (/user_code/node_modules/@google-cloud/bigquery/node_modules/request/request.js:186:22) at emitTwo (events.js:106:13) at Request.emit (events.js:191:7) at Request.<anonymous> (/user_code/node_modules/@google-cloud/bigquery/node_modules/request/request.js:1163:10) at emitOne (events.js:96:13) at Request.emit (events.js:188:7) errors: [ { errors: [Object], row: [Object] } ], response: { kind: 'bigquery#tableDataInsertAllResponse', insertErrors: [ [Object] ] }, message: 'A failure occurred during this request.' }

**Comment by jjgamboa123** [comment]
Isue resolved ! Bad spelling !!
