### ISSUE TITLE
JSON error

### ISSUE THREAD

**Issue by bimbayo** [googlecodelabs/iot-data-pipeline#14]
Hi, 
I got this error from the command 'gcloud functions logs read function-weatherPubSubToBQ'

function-weatherPubSubToBQ  530804522967360  2019-04-27 01:52:25.193  SyntaxError: Unexpected token ' in JSON at position 1
                                                                                 at JSON.parse (<anonymous>)
                                                                                 at exports.subscribe (/srv/index.js:15:25)
                                                                                 at /worker/worker.js:825:24
                                                                                 at <anonymous>
                                                                                 at process._tickDomainCallback (internal/process/next_tick.js

**Comment by rjwdata** [comment]
I am getting the same error, were you able to fix this?

**Comment by vmulholl** [comment]
@bimbayo @rjwdata 
Were you able to find a solution?

**Comment by jsalaman** [comment]
Guys while Im not using a Raspberry it seems I faced similar error while injecting directly into the pubSub topic to trigger the function.

The sample code works only - Im still trying to figured out why - with NodeJS-6

If you created the cloud function using latest NodeJS-8 engine, then you wont be able to make it into BigQuery.

Simply change the engine for the cloud function to NodeJS-6.

**Comment by lkj19zpdiDDe** [comment]
The Google Cloud Function API for pub/sub triggers changed between NodeJS-6 and NodeJS-8 and higher. 

Code for the latest runtime is below. 

```
/**
 * Background Cloud Function to be triggered by PubSub.
 *
 * @param {object} event The Cloud Functions event.
 * @param {function} callback The callback function.
 */
exports.subscribe = function (event, context) {
  const BigQuery = require('@google-cloud/bigquery');
  const projectId = "teamrun-204214"; //Enter your project ID here
  const datasetId = "weatherData"; //Enter your BigQuery dataset name here
  const tableId = "weatherDataTable"; //Enter your BigQuery table name here -- make sure it is setup correctly
  const PubSubMessage = event.data;
  // Incoming data is in JSON format
  const incomingData = PubSubMessage ? Buffer.from(PubSubMessage, 'base64').toString() : "{'sensorID':'na','timecollected':'1/1/1970 00:00:00','zipcode':'00000','latitude':'0.0','longitude':'0.0','temperature':'-273','humidity':'-1','dewpoint':'-273','pressure':'0'}";
  const jsonData = JSON.parse(incomingData);
  var rows = [jsonData];

  console.log(`Uploading data: ${JSON.stringify(rows)}`);

  // Instantiates a client
  const bigquery = BigQuery({
    projectId: projectId
  });

  // Inserts data into a table
  bigquery
    .dataset(datasetId)
    .table(tableId)
    .insert(rows)
    .then((foundErrors) => {
      rows.forEach((row) => console.log('Inserted: ', row));

      if (foundErrors && foundErrors.insertErrors != undefined) {
        foundErrors.forEach((err) => {
            console.log('Error: ', err);
        })
      }
    })
    .catch((err) => {
      console.error('ERROR:', err);
    });
  // [END bigquery_insert_stream]

};
```
