### ISSUE TITLE
Error message when BigQuery table field mis-spelled

### ISSUE THREAD

**Issue by nkolban** [googlecodelabs/iot-data-pipeline#9]
Despite a clear warning not to make a mistake in the BigQuery field names in this example, I did indeed make a typo.  I spelled the field `humidity` as `humidty`.  It took me a long time to find my error.   The associated stack-driver log entry (that was repeated) is copied at the end of this issue.

I am not expecting any resolution of this error as it was self inflicted.  The purpose of this issue is to record the error such that perhaps it may show up in a future search for some other user should they make a similar mistake and be guided to check the naming of their own fields. 

```
function-weatherPubSubToBQ
181904261563154
ERROR: { PartialFailureError: A failure occurred during this request. at /user_code/node_modules/@google-cloud/bigquery/src/table.js:1213:13 at Object.handleResp (/user_code/node_modules/@google-cloud/bigquery/node_modules/@google-cloud/common/src/util.js:135:3) at /user_code/node_modules/@google-cloud/bigquery/node_modules/@google-cloud/common/src/util.js:465:12 at Request.onResponse [as _callback] (/user_code/node_modules/@google-cloud/bigquery/node_modules/retry-request/index.js:198:7) at Request.self.callback (/user_code/node_modules/@google-cloud/bigquery/node_modules/request/request.js:185:22) at emitTwo (events.js:106:13) at Request.emit (events.js:191:7) at Request.<anonymous> (/user_code/node_modules/@google-cloud/bigquery/node_modules/request/request.js:1161:10) at emitOne (events.js:96:13) at Request.emit (events.js:188:7)
errors: [ { errors: [Object], row: [Object] } ],
response: { kind: 'bigquery#tableDataInsertAllResponse', insertErrors: [ [Object] ] },
message: 'A failure occurred during this request.' }
```

**Comment by nkolban** [comment]
Closing as no fix anticipated, issue logged merely for search and history tracking.
